name: Bug report
description: Report a reproducible bug
type: bug
body:
  - type: dropdown
    attributes:
      label: Affected component
      description: Select the affected Duende component
      options:
        - label: Duende.AccessTokenManagement
        - label: Duende.IdentityModel
        - label: Duende.IdentityModel.OidcClient
        - label: Other
  - type: input
    attributes:
      label: Version
      description: Specify the version of the affected component.
      placeholder: e.g., 7.0.2
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the issue.
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Additional context
      description: Any other information that may help.
